datasource:
  db:
    username: "root"
    password: "123456"
    driver: "org.sqlite.JDBC"
    url: "jdbc:sqlite:work/database/db.sqlite"

server:
  port: 7031
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,image/png,image/jpeg
    min-response-size: 2048

spring:
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: GMT+8
  application:
    name: "vrc-bitmap-led"

logging:
  charset:
    console: UTF-8
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%-5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
  config: "classpath:logback-spring.xml"
