{
  "formatVersion": "1.1",
  "component": {
    "url": "../../libui/0.1.9/libui-0.1.9.module",
    "group": "com.github.msink",
    "module": "libui",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "windows64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "libui.klib",
          "url": "libui-windows64-0.1.9.klib",
          "size": 5569760,
          "sha512": "24e8d08f4eed5ef709f1960deff280f5fe6be3755773b16e7f17112f0b2e05c58ae8043c8b5b0ea5b08344a2d07c99aff2e98da3cb586afc36677f357a773ec8",
          "sha256": "db111565cc68255d8bce3d745014929cde9ba61d720511b8f50ccb16fd3f5928",
          "sha1": "405f184a251ca1d108f9496127f9f40a19a1bf3f",
          "md5": "d6f25894e0107bf9b6122f926038c0a8"
        },
        {
          "name": "libui-cinterop-libui.klib",
          "url": "libui-windows64-0.1.9-cinterop-libui.klib",
          "size": 43463,
          "sha512": "343b4af7557fa5b16a9ca1ff5a9b64c0405c0d940bdd6950f72a09a30e59e8adcc0dbd3ed0ccc5e473d37bb6b12921d41abcdd733ce20498bc5607ca17acf65a",
          "sha256": "2aba9a37b8cf13a4c45a0c13caffc67dd9830ea3967f10b10385ce43e5dc9033",
          "sha1": "6587253dfa35121f67a1393fab8b4a7481cb18ab",
          "md5": "50a657bf81cc3654c4383e3885e5deda"
        }
      ]
    }
  ]
}
