{
  "formatVersion": "1.1",
  "component": {
    "url": "../../libui/0.1.9/libui-0.1.9.module",
    "group": "com.github.msink",
    "module": "libui",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "windows64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "libui.klib",
          "url": "libui-windows64-0.1.9.klib",
          "size": 5569881,
          "sha512": "ad4f4ab10c3b8719df25ae104c5a1cda8568c7129e236f9f885e1b63cc1707273733c59736eb121b599bf5e5d990c992dc80404a672b5978e177cc52c91b6d28",
          "sha256": "7b062883b52a1ccf2b70561cd4e491b861765c3ad66a5ad39275906ca36de43c",
          "sha1": "a9d51141f0a833ce422bf1d81fc5b500e16d18fb",
          "md5": "430543851662ff42ccf9831d3ce7c5c3"
        },
        {
          "name": "libui-cinterop-libui.klib",
          "url": "libui-windows64-0.1.9-cinterop-libui.klib",
          "size": 55799,
          "sha512": "b7ca6873becec51334ff1c3bd8d4bd50fbc08f8e1c84fe487a5e80f9c6124de3117b960a5f29090069d02d79f920c7425965110897060d5965e5e7f651c927e0",
          "sha256": "8b41f5e970784d689cc8f76b81b1e4e844d23d53f2cf76e1af74fa57abff3e97",
          "sha1": "a1bda9884e3cde4cb3b765ae6d72a15d8ae58a20",
          "md5": "c186d8d89c79dd3ab74ba2f8508b0271"
        }
      ]
    }
  ]
}
